### ISSUE TITLE
Issue with process.stderr.fd

### ISSUE THREAD

**Issue by Danm72** [sanity-io/assist#3]
`Uncaught error: Cannot read properties of undefined (reading 'fd')
[http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_assist.js?](http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_assist.js?v=ceec9aa0:1807:112)`

https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1695845847350879?thread_ts=1695369812.598709&cid=C9Z7RC3V1

**Comment by kmelve** [comment]
We have discovered a regression in `v1.2.0`; the temporary fix is to install `1.1.4`: 

```sh
npm i @sanity/assist@1.1.4 --save-exact
```

**Comment by stipsan** [comment]
Could you try https://github.com/sanity-io/assist/releases/tag/v1.2.1 ?
